import { SearyaApi } from './api.js';
const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];
const esc=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const money=(cents,currency='usd')=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:String(currency).toUpperCase()}).format(Number(cents||0)/100);
const date=value=>value?new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—';
const toolNames={qr:'QR kod','qr-code':'QR kod','time_card':'Zaman kartı',time:'Zaman kartı',invoice:'Fatura',quote:'Teklif',receipt:'Makbuz',digital_business_card:'Dijital kart',card:'Dijital kart',email_signature:'E-posta imzası','email-signature':'E-posta imzası',expense_tracker:'Gider takibi','expense-tracker':'Gider takibi',profit_margin:'Kâr marjı','profit-margin':'Kâr marjı',unknown:'Bilinmiyor'};
const eventNames={tool_opened:'Aracı açtı',tool_completed:'Aracı tamamladı',tool_exported:'Dosya dışa aktardı',tool_saved:'Çalışmasını kaydetti',signup_completed:'Yeni hesap oluşturdu',checkout_started:'Ödemeyi başlattı',checkout_failed:'Ödeme başarısız oldu',auth_failed:'Giriş başarısız oldu',ui_error:'Arayüz hatası'};
const empty=text=>`<div class="empty">${esc(text)}</div>`;let data;let loading=false;

const sectionCopy={dashboard:['Genel bakış','Gerçek kullanıcı, araç ve gelir verileri'],tools:['Araç kullanımı','Hangi araçların değer ürettiğini görün'],acquisition:['Trafik ve dönüşüm','Reklam kaynaklarını ve dönüşüm hunisini ölçün'],users:['Kullanıcılar','Üyeleri ve kullanım durumlarını yönetin'],memberships:['Üyelikler','Pro plan ve ödeme hareketlerini takip edin'],feedback:['Geri bildirim','Kullanıcı mesajlarını okuyun ve sonuçlandırın'],operations:['Sistem durumu','Hata ve e-posta kayıtlarını takip edin'],activity:['Canlı hareketler','Ziyaretçilerin anonim ürün hareketleri']};
$$('nav button').forEach(button=>button.addEventListener('click',()=>{$$('nav button,.panel').forEach(item=>item.classList.remove('active'));button.classList.add('active');$(`#${button.dataset.section}`).classList.add('active');const copy=sectionCopy[button.dataset.section];$('#page-title').textContent=copy[0];$('#page-subtitle').textContent=copy[1];}));
$$('[data-search]').forEach(input=>input.addEventListener('input',()=>{const query=input.value.toLocaleLowerCase('tr-TR');$$(`#${input.dataset.search} tr`).forEach(row=>row.hidden=!row.textContent.toLocaleLowerCase('tr-TR').includes(query));}));

function metric(label,value,note='',tone=''){return `<article class="metric ${tone}"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></article>`;}
function tools(){return data.analytics?.tools||[];}
function render(){
  const c=data.counts;const presence=data.analytics?.presence||{};const funnel=data.analytics?.funnel||{};
  $('#live-metrics').innerHTML=metric('Şu an aktif',presence.activeNow||0,'Son 2 dakika','metric-live')+metric('Bugün gelen',presence.enteredToday||0,'Benzersiz oturum')+metric('Bugün ayrılan',presence.exitedToday||0,'Çıkış veya zaman aşımı');
  $('#live-updated').textContent=`Güncellendi ${new Intl.DateTimeFormat('tr-TR',{timeStyle:'medium'}).format(new Date(presence.updatedAt||Date.now()))}`;
  $('#metrics').innerHTML=metric('Bugünkü ziyaretçi',c.visitorsToday,'Benzersiz')+metric('7 günlük ziyaretçi',c.visitors7d,`${c.pageViews7d} sayfa görüntüleme`)+metric('Toplam kullanıcı',c.users,`Bugün +${c.usersToday}`)+metric('Aktif Pro üye',c.activeSubscribers||0,'Ödeme durumu aktif')+metric('Bugünkü tamamlamalar',c.toolCompletionsToday||0,'Araç sonuçları')+metric('Kayıtlı çalışmalar',c.savedItems||0,'Kullanıcı bulutu')+metric('Toplam gelir',money(c.revenueCents),'Tools üyelikleri');
  const max=Math.max(1,...data.daily.flatMap(item=>[item.visitors,item.signups]));$('#chart').innerHTML=data.daily.map(item=>`<button class="day" type="button" data-chart-day="${item.day}"><span class="bars"><i class="bar" title="${item.visitors} ziyaretçi" style="height:${Math.max(3,item.visitors/max*100)}%"></i><i class="bar signup" title="${item.signups} kayıt" style="height:${Math.max(3,item.signups/max*100)}%"></i></span><label>${new Date(item.day+'T12:00:00').toLocaleDateString('tr-TR',{weekday:'short'})}</label></button>`).join('');
  $('#dashboard-tools').innerHTML=tools().slice(0,6).map(item=>`<div class="insight-row"><div><strong>${esc(toolNames[item.tool]||item.tool)}</strong><small>${item.users} benzersiz kullanıcı</small></div><div><b>${item.opened}</b><i style="--fill:${Math.min(100,item.opened/Math.max(1,...tools().map(tool=>tool.opened))*100)}%"></i></div></div>`).join('')||empty('Araç verisi henüz oluşmadı.');
  const stages=[['Ziyaretçi',funnel.visitors||0],['Araç açan',funnel.toolStarts||0],['Sonuç alan',funnel.toolCompletions||0],['Kayıt olan',funnel.signups||0],['Ödemeye geçen',funnel.checkouts||0]];$('#dashboard-funnel').innerHTML=stages.map(([label,value],index)=>`<div><span>${index+1}</span><strong>${label}</strong><b>${value}</b></div>`).join('');
  $('#tool-metrics').innerHTML=metric('Toplam araç açılışı',tools().reduce((s,i)=>s+i.opened,0),'Son 30 gün')+metric('Tamamlanan işler',tools().reduce((s,i)=>s+i.completed,0),'Değer anı')+metric('Dışa aktarılan',tools().reduce((s,i)=>s+i.exported,0),'PDF, CSV, QR, vCard')+metric('Buluta kaydedilen',tools().reduce((s,i)=>s+i.saved,0),'Hesaba kayıt');
  $('#tool-table').innerHTML=tools().map(item=>`<tr><td><strong>${esc(toolNames[item.tool]||item.tool)}</strong><small>${item.users} benzersiz kullanıcı</small></td><td>${item.opened}</td><td>${item.completed}</td><td>${item.exported}</td><td>${item.saved}</td><td><span class="rate">${item.opened?Math.round(item.completed/item.opened*100):0}%</span></td></tr>`).join('')||`<tr><td colspan="6">${empty('Henüz araç kullanımı yok.')}</td></tr>`;
  const rate=value=>funnel.visitors?`${(Number(value||0)/funnel.visitors*100).toFixed(1)}%`:'0%';$('#funnel-metrics').innerHTML=metric('30 günlük ziyaretçi',funnel.visitors||0,'Başlangıç')+metric('Araç kullanan',funnel.toolStarts||0,rate(funnel.toolStarts))+metric('Sonuç alan',funnel.toolCompletions||0,rate(funnel.toolCompletions))+metric('Kayıt olan',funnel.signups||0,rate(funnel.signups))+metric('Ödemeye başlayan',funnel.checkouts||0,rate(funnel.checkouts));
  $('#campaign-table').innerHTML=(data.analytics?.campaigns||[]).map(item=>`<tr><td><strong>${esc(item.source||'direct')}</strong></td><td>${esc(item.medium||'direct')}</td><td>${esc(item.campaign||'—')}</td><td>${item.visitors}</td><td>${item.signups}</td><td>${item.toolStarts||item.listings||0}</td><td>${item.checkouts||item.conversations||0}</td></tr>`).join('')||`<tr><td colspan="7">${empty('UTM kampanya verisi henüz yok.')}</td></tr>`;
  $('#user-table').innerHTML=(data.users||[]).map(user=>`<tr><td><strong>${esc(user.name)}</strong><small>${esc(user.email)}</small></td><td><span class="badge ${user.plan==='pro'?'paid':''}">${user.plan==='pro'?'PRO':'FREE'}</span></td><td>${user.savedItems||0}</td><td>${date(user.createdAt)}</td><td>${date(user.lastSeenAt)}</td><td><span class="badge ${user.status}">${user.status==='active'?'Aktif':'Askıda'}</span></td><td>${user.isAdmin?'—':`<button class="action ${user.status==='active'?'danger':'good'}" data-user-status="${user.id}" data-status="${user.status==='active'?'suspended':'active'}">${user.status==='active'?'Askıya al':'Etkinleştir'}</button>`}</td></tr>`).join('');
  $('#membership-metrics').innerHTML=metric('Aktif Pro',c.activeSubscribers||0,'Güncel üyelik')+metric('Başarılı ödeme',c.paidPurchases||0,'Tüm zamanlar')+metric('Toplam gelir',money(c.revenueCents),'USD üyelikler')+metric('Kullanıcı başına gelir',c.users?money(c.revenueCents/c.users):money(0),'Toplam kullanıcı bazında');
  $('#purchase-table').innerHTML=(data.purchases||[]).map(item=>`<tr><td><strong>${esc(item.userName)}</strong><small>${esc(item.userEmail)}</small></td><td>${esc(item.packageKey.replace('tools_pro_','Pro '))}</td><td>${money(item.amountCents,item.currency)}</td><td><span class="badge ${item.status}">${item.status==='paid'?'Ödendi':esc(item.status)}</span></td><td>${date(item.createdAt)}</td></tr>`).join('')||`<tr><td colspan="5">${empty('Henüz Tools üyelik ödemesi yok.')}</td></tr>`;
  const feedback=data.feedback||[];const feedbackNew=feedback.filter(item=>item.status==='new').length;const feedbackResolved=feedback.filter(item=>item.status==='resolved').length;
  $('#feedback-metrics').innerHTML=metric('Yeni mesaj',feedbackNew,'Yanıt bekliyor')+metric('Toplam mesaj',feedback.length,'Son 200 kayıt')+metric('Sonuçlanan',feedbackResolved,'Tamamlandı')+metric('Şikâyet',feedback.filter(item=>item.feedbackType==='complaint').length,'Toplam');
  $('#feedback-table').innerHTML=feedback.map(item=>`<tr><td><strong>${esc(item.name)}</strong><small><a href="mailto:${esc(item.email)}">${esc(item.email)}</a></small></td><td>${esc({suggestion:'Öneri',advice:'Tavsiye',complaint:'Şikâyet',other:'Diğer'}[item.feedbackType]||item.feedbackType)}</td><td class="message-cell">${esc(item.message)}</td><td>${esc(item.pagePath)}</td><td><span class="badge ${item.status}">${item.status==='new'?'Yeni':item.status==='read'?'Okundu':'Sonuçlandı'}</span></td><td>${date(item.createdAt)}</td><td><div class="actions"><button class="action" data-feedback-status="${item.id}" data-status="read">Okundu</button><button class="action good" data-feedback-status="${item.id}" data-status="resolved">Sonuçlandır</button></div></td></tr>`).join('')||`<tr><td colspan="7">${empty('Henüz geri bildirim yok.')}</td></tr>`;
  const errors=data.analytics?.errors||[];const emails=data.emailLogs||[];
  $('#operation-metrics').innerHTML=metric('Son hata',errors.length,'En fazla 100 kayıt',errors.length?'danger':'')+metric('Gönderilen e-posta',emails.filter(item=>item.status==='sent').length,'Son 100 deneme')+metric('Başarısız e-posta',emails.filter(item=>item.status==='failed').length,'Kontrol gerekli')+metric('E-posta ayarı',emails.some(item=>item.status==='not_configured')?'Eksik':'Etkin','Resend durumu');
  $('#error-feed').innerHTML=errors.map(item=>`<article><i class="ph-bold ph-warning-circle"></i><div><strong>${esc(eventNames[item.eventName]||item.eventName)}</strong><small>${esc(item.userEmail||`Anonim ${String(item.visitorId||'').slice(0,8)}`)} · ${esc(item.metadata?.reason||item.metadata?.code||'Ayrıntı yok')}</small></div><time>${date(item.createdAt)}</time></article>`).join('')||empty('Kayıtlı hata yok.');
  $('#email-feed').innerHTML=emails.map(item=>`<article><i class="ph-bold ${item.status==='sent'?'ph-check-circle':'ph-warning-circle'}"></i><div><strong>${esc(item.subject)}</strong><small>${esc(item.recipient)}${item.errorMessage?` · ${esc(item.errorMessage)}`:''}</small></div><time><span class="badge ${item.status==='sent'?'resolved':'rejected'}">${item.status==='sent'?'Gönderildi':item.status==='failed'?'Başarısız':'Ayarsız'}</span><br>${date(item.createdAt)}</time></article>`).join('')||empty('Henüz e-posta kaydı yok.');
  $('#activity-feed').innerHTML=(data.analytics?.recentActivity||[]).map(item=>{const meta=item.metadata||{};return `<article><i class="ph-bold ${item.eventName==='signup_completed'?'ph-user-plus':item.eventName.includes('checkout')?'ph-credit-card':'ph-cursor-click'}"></i><div><strong>${esc(eventNames[item.eventName]||item.eventName)}</strong><small>${esc(item.userEmail||`Anonim ${String(item.visitorId||'').slice(0,8)}`)}${meta.tool?` · ${esc(toolNames[meta.tool]||meta.tool)}`:''}${meta.format?` · ${esc(meta.format)}`:''}</small></div><time>${date(item.createdAt)}</time></article>`;}).join('')||empty('Henüz hareket yok.');
}

document.addEventListener('click',async event=>{
  const dayButton=event.target.closest('[data-chart-day]');
  if(dayButton){const item=data.daily.find(row=>row.day===dayButton.dataset.chartDay);$$('[data-chart-day]').forEach(node=>node.classList.toggle('selected',node===dayButton));const conversion=item.visitors?(item.signups/item.visitors*100).toFixed(1):'0.0';$('#chart-stat').innerHTML=`<strong>${new Date(item.day+'T12:00:00').toLocaleDateString('tr-TR',{dateStyle:'full'})}</strong><span>${item.visitors} benzersiz ziyaretçi</span><span>${item.views} sayfa görüntüleme</span><span>${item.signups} yeni kayıt</span><span>%${conversion} kayıt dönüşümü</span>`;return;}
  const userButton=event.target.closest('[data-user-status]');
  const feedbackButton=event.target.closest('[data-feedback-status]');
  if(!userButton&&!feedbackButton)return;
  const button=userButton||feedbackButton;button.disabled=true;
  try{if(userButton)await SearyaApi.updateAdminUserStatus(userButton.dataset.userStatus,userButton.dataset.status);else await SearyaApi.updateAdminFeedbackStatus(feedbackButton.dataset.feedbackStatus,feedbackButton.dataset.status);await load({silent:true});}catch(error){alert(error.message||'İşlem tamamlanamadı.');button.disabled=false;}
});

async function load({silent=false}={}){if(loading)return;loading=true;if(!silent){$('#notice').className='notice';$('#notice').textContent='Veriler yükleniyor…';}try{data=await SearyaApi.adminOverview();render();$('#notice').classList.add('hidden');}catch(error){if(!silent){$('#notice').className='notice error';$('#notice').innerHTML=`Yönetici girişi gerekiyor. <a href="/">Ana sayfadan giriş yapın</a>`;}}finally{loading=false;}}
$('#refresh-btn').addEventListener('click',()=>load());load();setInterval(()=>{if(!document.hidden)load({silent:true});},15000);
