import { SearyaApi } from './api.js';
const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];
const esc=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const money=(cents,currency='usd')=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:String(currency).toUpperCase()}).format(Number(cents||0)/100);
const date=value=>value?new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—';
const toolNames={qr:'QR kod','qr-code':'QR kod','time_card':'Zaman kartı',time:'Zaman kartı',invoice:'Fatura',quote:'Teklif',receipt:'Makbuz',digital_business_card:'Dijital kart',card:'Dijital kart',email_signature:'E-posta imzası','email-signature':'E-posta imzası',expense_tracker:'Gider takibi','expense-tracker':'Gider takibi',profit_margin:'Kâr marjı','profit-margin':'Kâr marjı',unknown:'Bilinmiyor'};
const eventNames={tool_opened:'Aracı açtı',tool_completed:'Aracı tamamladı',tool_exported:'Dosya dışa aktardı',tool_saved:'Çalışmasını kaydetti',signup_completed:'Yeni hesap oluşturdu',checkout_started:'Ödemeyi başlattı',checkout_failed:'Ödeme başarısız oldu'};
const empty=text=>`<div class="empty">${esc(text)}</div>`;let data;let loading=false;

const sectionCopy={dashboard:['Genel bakış','Gerçek kullanıcı, araç ve gelir verileri'],tools:['Araç kullanımı','Hangi araçların değer ürettiğini görün'],acquisition:['Trafik ve dönüşüm','Reklam kaynaklarını ve dönüşüm hunisini ölçün'],users:['Kullanıcılar','Üyeleri ve kullanım durumlarını yönetin'],memberships:['Üyelikler','Pro plan ve ödeme hareketlerini takip edin'],activity:['Canlı hareketler','Ziyaretçilerin anonim ürün hareketleri']};
$$('nav button').forEach(button=>button.addEventListener('click',()=>{$$('nav button,.panel').forEach(item=>item.classList.remove('active'));button.classList.add('active');$(`#${button.dataset.section}`).classList.add('active');const copy=sectionCopy[button.dataset.section];$('#page-title').textContent=copy[0];$('#page-subtitle').textContent=copy[1];}));
$$('[data-search]').forEach(input=>input.addEventListener('input',()=>{const query=input.value.toLocaleLowerCase('tr-TR');$$(`#${input.dataset.search} tr`).forEach(row=>row.hidden=!row.textContent.toLocaleLowerCase('tr-TR').includes(query));}));

function metric(label,value,note='',tone=''){return `<article class="metric ${tone}"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></article>`;}
function tools(){return data.analytics?.tools||[];}
function render(){
  const c=data.counts;const presence=data.analytics?.presence||{};const funnel=data.analytics?.funnel||{};
  $('#live-metrics').innerHTML=metric('Şu an aktif',presence.activeNow||0,'Son 2 dakika','metric-live')+metric('Bugün gelen',presence.enteredToday||0,'Benzersiz oturum')+metric('Bugün ayrılan',presence.exitedToday||0,'Çıkış veya zaman aşımı');
  $('#live-updated').textContent=`Güncellendi ${new Intl.DateTimeFormat('tr-TR',{timeStyle:'medium'}).format(new Date(presence.updatedAt||Date.now()))}`;
  $('#metrics').innerHTML=metric('Bugünkü ziyaretçi',c.visitorsToday,'Benzersiz')+metric('7 günlük ziyaretçi',c.visitors7d,`${c.pageViews7d} sayfa görüntüleme`)+metric('Toplam kullanıcı',c.users,`Bugün +${c.usersToday}`)+metric('Aktif Pro üye',c.activeSubscribers||0,'Ödeme durumu aktif')+metric('Bugünkü tamamlamalar',c.toolCompletionsToday||0,'Araç sonuçları')+metric('Kayıtlı çalışmalar',c.savedItems||0,'Kullanıcı bulutu')+metric('Toplam gelir',money(c.revenueCents),'Tools üyelikleri');
  const max=Math.max(1,...data.daily.flatMap(item=>[item.visitors,item.signups]));$('#chart').innerHTML=data.daily.map(item=>`<div class="day"><div class="bars"><i class="bar" title="${item.visitors} ziyaretçi" style="height:${Math.max(3,item.visitors/max*100)}%"></i><i class="bar signup" title="${item.signups} kayıt" style="height:${Math.max(3,item.signups/max*100)}%"></i></div><label>${new Date(item.day+'T12:00:00').toLocaleDateString('tr-TR',{weekday:'short'})}</label></div>`).join('');
  $('#dashboard-tools').innerHTML=tools().slice(0,6).map(item=>`<div class="insight-row"><div><strong>${esc(toolNames[item.tool]||item.tool)}</strong><small>${item.users} benzersiz kullanıcı</small></div><div><b>${item.opened}</b><i style="--fill:${Math.min(100,item.opened/Math.max(1,...tools().map(tool=>tool.opened))*100)}%"></i></div></div>`).join('')||empty('Araç verisi henüz oluşmadı.');
  const stages=[['Ziyaretçi',funnel.visitors||0],['Araç açan',funnel.toolStarts||0],['Sonuç alan',funnel.toolCompletions||0],['Kayıt olan',funnel.signups||0],['Ödemeye geçen',funnel.checkouts||0]];$('#dashboard-funnel').innerHTML=stages.map(([label,value],index)=>`<div><span>${index+1}</span><strong>${label}</strong><b>${value}</b></div>`).join('');
  $('#tool-metrics').innerHTML=metric('Toplam araç açılışı',tools().reduce((s,i)=>s+i.opened,0),'Son 30 gün')+metric('Tamamlanan işler',tools().reduce((s,i)=>s+i.completed,0),'Değer anı')+metric('Dışa aktarılan',tools().reduce((s,i)=>s+i.exported,0),'PDF, CSV, QR, vCard')+metric('Buluta kaydedilen',tools().reduce((s,i)=>s+i.saved,0),'Hesaba kayıt');
  $('#tool-table').innerHTML=tools().map(item=>`<tr><td><strong>${esc(toolNames[item.tool]||item.tool)}</strong><small>${item.users} benzersiz kullanıcı</small></td><td>${item.opened}</td><td>${item.completed}</td><td>${item.exported}</td><td>${item.saved}</td><td><span class="rate">${item.opened?Math.round(item.completed/item.opened*100):0}%</span></td></tr>`).join('')||`<tr><td colspan="6">${empty('Henüz araç kullanımı yok.')}</td></tr>`;
  const rate=value=>funnel.visitors?`${(Number(value||0)/funnel.visitors*100).toFixed(1)}%`:'0%';$('#funnel-metrics').innerHTML=metric('30 günlük ziyaretçi',funnel.visitors||0,'Başlangıç')+metric('Araç kullanan',funnel.toolStarts||0,rate(funnel.toolStarts))+metric('Sonuç alan',funnel.toolCompletions||0,rate(funnel.toolCompletions))+metric('Kayıt olan',funnel.signups||0,rate(funnel.signups))+metric('Ödemeye başlayan',funnel.checkouts||0,rate(funnel.checkouts));
  $('#campaign-table').innerHTML=(data.analytics?.campaigns||[]).map(item=>`<tr><td><strong>${esc(item.source||'direct')}</strong></td><td>${esc(item.medium||'direct')}</td><td>${esc(item.campaign||'—')}</td><td>${item.visitors}</td><td>${item.signups}</td><td>${item.toolStarts||item.listings||0}</td><td>${item.checkouts||item.conversations||0}</td></tr>`).join('')||`<tr><td colspan="7">${empty('UTM kampanya verisi henüz yok.')}</td></tr>`;
  $('#user-table').innerHTML=(data.users||[]).map(user=>`<tr><td><strong>${esc(user.name)}</strong><small>${esc(user.email)}</small></td><td><span class="badge ${user.plan==='pro'?'paid':''}">${user.plan==='pro'?'PRO':'FREE'}</span></td><td>${user.savedItems||0}</td><td>${date(user.createdAt)}</td><td>${date(user.lastSeenAt)}</td><td><span class="badge ${user.status}">${user.status==='active'?'Aktif':'Askıda'}</span></td></tr>`).join('');
  $('#membership-metrics').innerHTML=metric('Aktif Pro',c.activeSubscribers||0,'Güncel üyelik')+metric('Başarılı ödeme',c.paidPurchases||0,'Tüm zamanlar')+metric('Toplam gelir',money(c.revenueCents),'USD üyelikler')+metric('Kullanıcı başına gelir',c.users?money(c.revenueCents/c.users):money(0),'Toplam kullanıcı bazında');
  $('#purchase-table').innerHTML=(data.purchases||[]).map(item=>`<tr><td><strong>${esc(item.userName)}</strong><small>${esc(item.userEmail)}</small></td><td>${esc(item.packageKey.replace('tools_pro_','Pro '))}</td><td>${money(item.amountCents,item.currency)}</td><td><span class="badge ${item.status}">${item.status==='paid'?'Ödendi':esc(item.status)}</span></td><td>${date(item.createdAt)}</td></tr>`).join('')||`<tr><td colspan="5">${empty('Henüz Tools üyelik ödemesi yok.')}</td></tr>`;
  $('#activity-feed').innerHTML=(data.analytics?.recentActivity||[]).map(item=>{const meta=item.metadata||{};return `<article><i class="ph-bold ${item.eventName==='signup_completed'?'ph-user-plus':item.eventName.includes('checkout')?'ph-credit-card':'ph-cursor-click'}"></i><div><strong>${esc(eventNames[item.eventName]||item.eventName)}</strong><small>${esc(item.userEmail||`Anonim ${String(item.visitorId||'').slice(0,8)}`)}${meta.tool?` · ${esc(toolNames[meta.tool]||meta.tool)}`:''}${meta.format?` · ${esc(meta.format)}`:''}</small></div><time>${date(item.createdAt)}</time></article>`;}).join('')||empty('Henüz hareket yok.');
}

async function load({silent=false}={}){if(loading)return;loading=true;if(!silent){$('#notice').className='notice';$('#notice').textContent='Veriler yükleniyor…';}try{data=await SearyaApi.adminOverview();render();$('#notice').classList.add('hidden');}catch(error){if(!silent){$('#notice').className='notice error';$('#notice').innerHTML=`Yönetici girişi gerekiyor. <a href="/">Ana sayfadan giriş yapın</a>`;}}finally{loading=false;}}
$('#refresh-btn').addEventListener('click',()=>load());load();setInterval(()=>{if(!document.hidden)load({silent:true});},15000);
